<?php

declare(strict_types=1);

use Esse\Auth;
use Esse\AuditLog;
use Esse\Updater;

// Only forge/admin with manage_settings can run updates
if (!Auth::meetsRole('forge') && !Auth::can('manage_settings')) {
    http_response_code(403); exit;
}

// Validate short-lived run token (generated by POST /admin/update/prepare)
$token = $_GET['run_token'] ?? '';
if (empty($_SESSION['update_run_token']) || !hash_equals($_SESSION['update_run_token'], $token)) {
    http_response_code(403); exit;
}
unset($_SESSION['update_run_token']); // one-time use

// SSE headers
header('Content-Type: text/event-stream');
header('Cache-Control: no-cache');
header('X-Accel-Buffering: no');

set_time_limit(0);
ignore_user_abort(true);

// Flush output immediately
while (ob_get_level()) ob_end_flush();
ob_implicit_flush(true);

function sse(string $message, string $type = 'info'): void
{
    echo 'data: ' . json_encode(['type' => $type, 'message' => $message]) . "\n\n";
    flush();
}

// Padding: many hosting setups proxy PHP through Apache (mod_proxy_fcgi) and/or nginx,
// both of which buffer small responses (a few KB) until the script ends. Without this,
// the SSE stream arrives all at once at the end instead of live. A leading comment
// block larger than typical proxy buffers (8-32 KB) forces an immediate flush through.
echo str_repeat(': padding' . str_repeat(' ', 2000) . "\n", 33) . "\n";
flush();

try {
    // 1. Get latest release info (respect pre-release setting)
    $ts            = \Esse\DB::table('settings');
    $inclPrerel    = \Esse\DB::value("SELECT `value` FROM `{$ts}` WHERE `key` = 'update_prerelease'") === '1';

    sse('Prüfe auf verfügbare Updates...');
    $info = Updater::checkForUpdate($inclPrerel);

    if (!$info) {
        sse('GitHub nicht erreichbar.', 'error');
        exit;
    }

    if (!Updater::isNewer($info['version'], ESSE_VERSION)) {
        sse('Kein Update verfügbar — bereits aktuell.', 'info');
        sse('done', 'done');
        exit;
    }

    sse("Update auf v{$info['version']} wird gestartet...");

    // 2. Backup
    sse('─── Schritt 1: Backup ───');
    Updater::createBackup(fn($msg) => sse($msg), 'pre-update');
    sse('Backup abgeschlossen.', 'success');

    // 3. Download
    sse('─── Schritt 2: Download ───');
    $zipPath = Updater::download($info['download_url'], fn($msg) => sse($msg));
    sse('Download abgeschlossen.', 'success');

    // 4. Apply
    sse('─── Schritt 3: Update anwenden ───');
    Updater::apply($zipPath, fn($msg) => sse($msg));
    sse('Dateien aktualisiert.', 'success');

    // 5. Clear update cache
    $cache = ESSE_PRIVATE_PATH . '/storage/cache/update_check.json';
    @unlink($cache);

    // 6. Update ESSE_VERSION in local.php if it overrides the version
    $localPhp = ESSE_ROOT . '/local.php';
    if (file_exists($localPhp)) {
        $localContent = file_get_contents($localPhp);
        if (str_contains($localContent, 'ESSE_VERSION')) {
            $newVersion = ltrim($info['version'], 'v');
            $updated = preg_replace(
                "/define\('ESSE_VERSION',\s*'[^']+'\)/",
                "define('ESSE_VERSION', '{$newVersion}')",
                $localContent
            );
            if ($updated && $updated !== $localContent) {
                file_put_contents($localPhp, $updated);
                sse("Version in local.php auf {$newVersion} aktualisiert.");
            }
        }
    }

    sse("─────────────────────────────────");
    sse("ESSE CMS v{$info['version']} wurde erfolgreich installiert.", 'success');
    sse('Seite wird neu geladen...', 'info');
    sse('done', 'done');

    AuditLog::record('self_update', Auth::id(), Auth::user()['email'] ?? null, [
        'from' => ESSE_VERSION,
        'to'   => $info['version'],
    ]);

} catch (\Throwable $e) {
    sse('Fehler: ' . $e->getMessage(), 'error');
    sse('Update abgebrochen. Das Backup liegt in storage/backups/.', 'error');

    AuditLog::record('self_update_failed', Auth::id(), Auth::user()['email'] ?? null, [
        'from'  => ESSE_VERSION,
        'to'    => $info['version'] ?? null,
        'error' => $e->getMessage(),
    ]);
}
